[package]
name = "soldering-guest"
version = "1.1.0"
edition = "2021"

[dependencies]
zkm-zkvm = { git = "https://github.com/ProjectZKM/Ziren", branch = "v1.2.5-blake3", features = ["embedded"] }
verifiable-circuit-babe = { path = "../../../verifiable-circuit-babe" }

[features]
imm-wrap-vk = ["zkm-zkvm/imm-wrap-vk"]
