use crate::utils::h_256;
use serde::{Deserialize, Serialize};
#[cfg(not(target_os = "zkvm"))]
use zkm_sdk::ZKMProofWithPublicValues;

pub type SolderedWire = ([u8; 16], [u8; 16]);
pub type InstancesWires = Vec<SolderedWire>;
pub type Sha256Commit = [u8; 32];

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct SolderedWiresInput(pub Vec<InstancesWires>);

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct SolderedLabelsData {
    pub deltas: Vec<Vec<([u8; 16], [u8; 16])>>,
    pub base_commitment: Vec<(Sha256Commit, Sha256Commit)>,
    pub commitments: Vec<Vec<(Sha256Commit, Sha256Commit)>>,
}

/// This struct represents for the STARK Proof generated by Verifier during soldering.
#[cfg(not(target_os = "zkvm"))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SolderingProof {
    pub proof: ZKMProofWithPublicValues,
}

#[cfg(not(target_os = "zkvm"))]
impl SolderingProof {
    pub fn output(&self) -> Result<SolderedLabelsData, String> {
        bincode::deserialize(self.proof.public_values.as_slice())
            .map_err(|e| format!("failed to decode soldering public values: {e}"))
    }
}

// Offchain data that Verifier sends to Prover after Soldering.
#[cfg(not(target_os = "zkvm"))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SolderingData {
    pub finalized_indices: Vec<usize>,
    pub soldering_proof: SolderingProof,
}

/// Called by the zkVM guest.
pub fn soldering_guest_compute(input: &SolderedWiresInput) -> SolderedLabelsData {
    let instances = &input.0;
    assert!(!instances.is_empty(), "at least one instance required");

    let base = &instances[0];

    let base_commitment = base.iter().map(|(l0, l1)| (h_256(l0), h_256(l1))).collect();

    let mut deltas = Vec::with_capacity(instances.len() - 1);
    let mut commitments = Vec::with_capacity(instances.len() - 1);

    let delta = |a: &[u8; 16], b: &[u8; 16]| -> [u8; 16] {
        let mut res = [0u8; 16];
        for i in 0..16 {
            res[i] = a[i] ^ b[i];
        }
        res
    };

    for inst in instances[1..].iter() {
        deltas.push(
            inst.iter()
                .zip(base.iter())
                .map(|((li0, li1), (b0, b1))| (delta(li0, b0), delta(li1, b1)))
                .collect(),
        );
        commitments.push(inst.iter().map(|(l0, l1)| (h_256(l0), h_256(l1))).collect());
    }

    SolderedLabelsData { base_commitment, deltas, commitments }
}

/// Build `SolderedWiresInput` from the verifier's finalized instances.
/// `instances[0]` = base (finalized_indices[0]), `instances[1..]` = non-base in order.
#[cfg(not(target_os = "zkvm"))]
pub fn build_soldered_wires_input(
    verifier: &crate::verifier::BABEVerifier,
    finalized_indices: &[usize],
) -> SolderedWiresInput {
    SolderedWiresInput(
        finalized_indices
            .iter()
            .map(|&idx| {
                let ls = verifier.light_secrets_for(idx);
                let delta = ls.delta;
                let encoding_keys = ls.input_0labels;

                (0..2)
                    .flat_map(|i| {
                        encoding_keys[i]
                            .iter()
                            .map(move |&ek| (ek.0, (ek ^ delta[i]).0))
                    })
                    .collect::<Vec<_>>()
            })
            .collect(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn wire(l0: u8, l1: u8) -> SolderedWire {
        ([l0; 16], [l1; 16])
    }

    #[test]
    fn test_soldering_guest_compute() {
        let base: InstancesWires = vec![wire(0x11, 0x22), wire(0x33, 0x44)];
        let inst1: InstancesWires = vec![wire(0xAA, 0xBB), wire(0xCC, 0xDD)];
        let inst2: InstancesWires = vec![wire(0x01, 0x02), wire(0x03, 0x04)];

        let input = SolderedWiresInput(vec![base.clone(), inst1.clone(), inst2.clone()]);
        let out = soldering_guest_compute(&input);

        // base_commitment: SHA256 of each base label, in order.
        let expected_base_commitment: Vec<_> = base
            .iter()
            .map(|(l0, l1)| (h_256(l0), h_256(l1)))
            .collect();
        assert_eq!(out.base_commitment, expected_base_commitment);

        // deltas/commitments: one entry per non-base instance, in order.
        assert_eq!(out.deltas.len(), 2);
        assert_eq!(out.commitments.len(), 2);

        // Hand-computed XOR: 0x11^0xAA=0xBB, 0x22^0xBB=0x99, 0x33^0xCC=0xFF, 0x44^0xDD=0x99.
        assert_eq!(out.deltas[0], vec![([0xBB; 16], [0x99; 16]), ([0xFF; 16], [0x99; 16])]);
        // 0x11^0x01=0x10, 0x22^0x02=0x20, 0x33^0x03=0x30, 0x44^0x04=0x40.
        assert_eq!(out.deltas[1], vec![([0x10; 16], [0x20; 16]), ([0x30; 16], [0x40; 16])]);

        let expected_commitments1: Vec<_> = inst1.iter().map(|(l0, l1)| (h_256(l0), h_256(l1))).collect();
        let expected_commitments2: Vec<_> = inst2.iter().map(|(l0, l1)| (h_256(l0), h_256(l1))).collect();
        assert_eq!(out.commitments[0], expected_commitments1);
        assert_eq!(out.commitments[1], expected_commitments2);
    }

    #[test]
    #[should_panic(expected = "at least one instance required")]
    fn test_soldering_guest_compute_empty_panics() {
        soldering_guest_compute(&SolderedWiresInput(vec![]));
    }
}
