[package]
name = "verifiable-circuit"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
zkm-zkvm = { git = "https://github.com/ProjectZKM/Ziren" } 
garbled-snark-verifier = { workspace = true } 
